#!/usr/bin/env bash

username=$(whoami)

if [ $username == "root" ]; then
    echo "Do not run as root"
fi

sudo mkdir -p /etc/sudoers.d

cat > sudo-intel-backlight << EOF
$username ALL=(ALL) NOPASSWD: tee /sys/class/backlight/intel_backlight/brightness
$username ALL=(ALL) NOPASSWD: cat /sys/class/backlight/intel_backlight/max_brightness
$username ALL=(ALL) NOPASSWD: cat /sys/class/backlight/intel_backlight/actual_brightness
EOF

sudo chown root:root sudo-intel-backlight
sudo chmod 440 sudo-intel-backlight

sudo cp sudo-intel-backlight /etc/sudoers.d/.
sudo rm sudo-intel-backlight
